name: Create docs README

on:
  workflow_dispatch:
    inputs:
      commit_message:
        description: 'Commit message'
        required: false
        default: 'Add docs/README.md'

jobs:
  create-file:
    runs-on: ubuntu-latest
    steps:
      - name: Create or update docs/README.md on add/docs-readme
        uses: peter-evans/create-or-update-file@v4
        with:
          path: docs/README.md
          commit-message: ${{ github.event.inputs.commit_message }}
          committer: GitHub Actions <actions@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          content: |
            # Design System

            This repository contains components, tokens, and guidelines for the Design System.

            ## Structure

            - tokens/ — design tokens (colors, spacing, typography)
            - components/ — UI components
            - docs/ — documentation and usage examples

            ## Contributing

            1. Fork the repo and create a topic branch.
            2. Run tests and linters before opening a PR.
            3. Follow the component API and token naming conventions.

            ## Contact

            Maintainer: hamzashaikhwork
          branch: add/docs-readme
